// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: paxos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         []int64                `protobuf:"varint,1,rep,packed,name=round,proto3" json:"round,omitempty"`
	InstanceId    int64                  `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareRequest) GetRound() []int64 {
	if x != nil {
		return x.Round
	}
	return nil
}

func (x *PrepareRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type PromiseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         []int64                `protobuf:"varint,1,rep,packed,name=round,proto3" json:"round,omitempty"`
	Ack           bool                   `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	LastGoodRound []int64                `protobuf:"varint,3,rep,packed,name=last_good_round,json=lastGoodRound,proto3" json:"last_good_round,omitempty"`
	Value         int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	InstanceId    int64                  `protobuf:"varint,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromiseResponse) Reset() {
	*x = PromiseResponse{}
	mi := &file_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseResponse) ProtoMessage() {}

func (x *PromiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseResponse.ProtoReflect.Descriptor instead.
func (*PromiseResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *PromiseResponse) GetRound() []int64 {
	if x != nil {
		return x.Round
	}
	return nil
}

func (x *PromiseResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *PromiseResponse) GetLastGoodRound() []int64 {
	if x != nil {
		return x.LastGoodRound
	}
	return nil
}

func (x *PromiseResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PromiseResponse) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         []int64                `protobuf:"varint,1,rep,packed,name=round,proto3" json:"round,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	InstanceId    int64                  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptRequest) GetRound() []int64 {
	if x != nil {
		return x.Round
	}
	return nil
}

func (x *AcceptRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AcceptRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type AcceptedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         []int64                `protobuf:"varint,1,rep,packed,name=round,proto3" json:"round,omitempty"`
	Ack           bool                   `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	InstanceId    int64                  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedResponse) Reset() {
	*x = AcceptedResponse{}
	mi := &file_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedResponse) ProtoMessage() {}

func (x *AcceptedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedResponse.ProtoReflect.Descriptor instead.
func (*AcceptedResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptedResponse) GetRound() []int64 {
	if x != nil {
		return x.Round
	}
	return nil
}

func (x *AcceptedResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *AcceptedResponse) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	InstanceId    int64                  `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Command       []byte                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *CommitRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CommitRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *CommitRequest) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{5}
}

type GetLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartingIndex int64                  `protobuf:"varint,1,opt,name=starting_index,json=startingIndex,proto3" json:"starting_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogRequest) Reset() {
	*x = GetLogRequest{}
	mi := &file_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogRequest) ProtoMessage() {}

func (x *GetLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogRequest.ProtoReflect.Descriptor instead.
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *GetLogRequest) GetStartingIndex() int64 {
	if x != nil {
		return x.StartingIndex
	}
	return 0
}

type GetLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogEntry      []*LogEntry            `protobuf:"bytes,1,rep,name=log_entry,json=logEntry,proto3" json:"log_entry,omitempty"`
	CommitIndex   int64                  `protobuf:"varint,2,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	SnapshotData  []byte                 `protobuf:"bytes,3,opt,name=snapshot_data,json=snapshotData,proto3" json:"snapshot_data,omitempty"`
	SnapshotIndex int64                  `protobuf:"varint,4,opt,name=snapshot_index,json=snapshotIndex,proto3" json:"snapshot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogResponse) Reset() {
	*x = GetLogResponse{}
	mi := &file_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogResponse) ProtoMessage() {}

func (x *GetLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogResponse.ProtoReflect.Descriptor instead.
func (*GetLogResponse) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *GetLogResponse) GetLogEntry() []*LogEntry {
	if x != nil {
		return x.LogEntry
	}
	return nil
}

func (x *GetLogResponse) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *GetLogResponse) GetSnapshotData() []byte {
	if x != nil {
		return x.SnapshotData
	}
	return nil
}

func (x *GetLogResponse) GetSnapshotIndex() int64 {
	if x != nil {
		return x.SnapshotIndex
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Command       []byte                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

var File_paxos_proto protoreflect.FileDescriptor

const file_paxos_proto_rawDesc = "" +
	"\n" +
	"\vpaxos.proto\x12\x05paxos\"G\n" +
	"\x0ePrepareRequest\x12\x14\n" +
	"\x05round\x18\x01 \x03(\x03R\x05round\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\x03R\n" +
	"instanceId\"\x98\x01\n" +
	"\x0fPromiseResponse\x12\x14\n" +
	"\x05round\x18\x01 \x03(\x03R\x05round\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\bR\x03ack\x12&\n" +
	"\x0flast_good_round\x18\x03 \x03(\x03R\rlastGoodRound\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\x03R\n" +
	"instanceId\"\\\n" +
	"\rAcceptRequest\x12\x14\n" +
	"\x05round\x18\x01 \x03(\x03R\x05round\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\x03R\n" +
	"instanceId\"[\n" +
	"\x10AcceptedResponse\x12\x14\n" +
	"\x05round\x18\x01 \x03(\x03R\x05round\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\bR\x03ack\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\x03R\n" +
	"instanceId\"`\n" +
	"\rCommitRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\x03R\n" +
	"instanceId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\fR\acommand\"\x10\n" +
	"\x0eCommitResponse\"6\n" +
	"\rGetLogRequest\x12%\n" +
	"\x0estarting_index\x18\x01 \x01(\x03R\rstartingIndex\"\xad\x01\n" +
	"\x0eGetLogResponse\x12,\n" +
	"\tlog_entry\x18\x01 \x03(\v2\x0f.paxos.LogEntryR\blogEntry\x12!\n" +
	"\fcommit_index\x18\x02 \x01(\x03R\vcommitIndex\x12#\n" +
	"\rsnapshot_data\x18\x03 \x01(\fR\fsnapshotData\x12%\n" +
	"\x0esnapshot_index\x18\x04 \x01(\x03R\rsnapshotIndex\":\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12\x18\n" +
	"\acommand\x18\x02 \x01(\fR\acommand2\xb1\x01\n" +
	"\x05Paxos\x128\n" +
	"\aPrepare\x12\x15.paxos.PrepareRequest\x1a\x16.paxos.PromiseResponse\x127\n" +
	"\x06Accept\x12\x14.paxos.AcceptRequest\x1a\x17.paxos.AcceptedResponse\x125\n" +
	"\x06Commit\x12\x14.paxos.CommitRequest\x1a\x15.paxos.CommitResponse2D\n" +
	"\vLogRecovery\x125\n" +
	"\x06GetLog\x12\x14.paxos.GetLogRequest\x1a\x15.paxos.GetLogResponseB\x1dZ\x1bds_project/src/server/protob\x06proto3"

var (
	file_paxos_proto_rawDescOnce sync.Once
	file_paxos_proto_rawDescData []byte
)

func file_paxos_proto_rawDescGZIP() []byte {
	file_paxos_proto_rawDescOnce.Do(func() {
		file_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)))
	})
	return file_paxos_proto_rawDescData
}

var file_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_paxos_proto_goTypes = []any{
	(*PrepareRequest)(nil),   // 0: paxos.PrepareRequest
	(*PromiseResponse)(nil),  // 1: paxos.PromiseResponse
	(*AcceptRequest)(nil),    // 2: paxos.AcceptRequest
	(*AcceptedResponse)(nil), // 3: paxos.AcceptedResponse
	(*CommitRequest)(nil),    // 4: paxos.CommitRequest
	(*CommitResponse)(nil),   // 5: paxos.CommitResponse
	(*GetLogRequest)(nil),    // 6: paxos.GetLogRequest
	(*GetLogResponse)(nil),   // 7: paxos.GetLogResponse
	(*LogEntry)(nil),         // 8: paxos.LogEntry
}
var file_paxos_proto_depIdxs = []int32{
	8, // 0: paxos.GetLogResponse.log_entry:type_name -> paxos.LogEntry
	0, // 1: paxos.Paxos.Prepare:input_type -> paxos.PrepareRequest
	2, // 2: paxos.Paxos.Accept:input_type -> paxos.AcceptRequest
	4, // 3: paxos.Paxos.Commit:input_type -> paxos.CommitRequest
	6, // 4: paxos.LogRecovery.GetLog:input_type -> paxos.GetLogRequest
	1, // 5: paxos.Paxos.Prepare:output_type -> paxos.PromiseResponse
	3, // 6: paxos.Paxos.Accept:output_type -> paxos.AcceptedResponse
	5, // 7: paxos.Paxos.Commit:output_type -> paxos.CommitResponse
	7, // 8: paxos.LogRecovery.GetLog:output_type -> paxos.GetLogResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_paxos_proto_init() }
func file_paxos_proto_init() {
	if File_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paxos_proto_rawDesc), len(file_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_paxos_proto_goTypes,
		DependencyIndexes: file_paxos_proto_depIdxs,
		MessageInfos:      file_paxos_proto_msgTypes,
	}.Build()
	File_paxos_proto = out.File
	file_paxos_proto_goTypes = nil
	file_paxos_proto_depIdxs = nil
}
